### ISSUE TITLE
Feature request: CLI command

### ISSUE THREAD

**Issue by ursbraem** [nhovratov/mask_permissions#4]
Would you be willing to add a console command? 

So the mask permissions can be added by the deploy script (github action, bitbucket pipeline, etc) or by composer "scripts" command when deploying.

We could chip in some sponsoring.

**Comment by nhovratov** [comment]
There already is a console command: https://github.com/nhovratov/mask_permissions/blob/master/Classes/Command/MaskPermissionsCommand.php

Usage: `maskpermissions:update <beUserGroupId>`

It's not documented well, sorry. Will add it to the Readme.

**Comment by ursbraem** [comment]
Fantastic! I tried to call it as such from composer.json but that doesn't seem to be right.

![ScreenShot 2023-03-22 at 09 52 46@2x](https://user-images.githubusercontent.com/1446443/226851221-adeb35cd-adaf-417d-a0be-07ae9071abe2.jpg)

Can you nudge me in the right direction?

**Comment by nhovratov** [comment]
@ursbraem I just released a new version of this extension, try to update it and run the command again. There was a type error when providing the group.

**Comment by ursbraem** [comment]
It works flawlessly, thank you!!
